Dockerfile

build: edit build args for fips friendly build

---

config/rhoai/binding_admin_roles.yaml
config/rhoai/kustomization.yaml

/kind feature
binding admin roles in Kueue
Fixes # https://issues.redhat.com/browse/RHOAIENG-2047
```release-note
```

CARRY: Bind admin roles in Kueue

---

config/components/manager/manager.yaml
config/components/webhook/service.yaml
config/rhoai/kustomization.yaml
config/rhoai/monitor.yaml

Fixes https://issues.redhat.com/browse/RHOAIENG-3431.

DROP: Use uniquely identifying labels

---

config/rhoai/kustomization.yaml
config/rhoai/webhook_network_policy.yaml

Fixes https://issues.redhat.com/browse/RHOAIENG-3415.
Depends on #18.

CARRY: Add Kueue webhook NetworkPolicy

---

test/util/e2e.go

Change namespace to opendatahub to run tests with rhoai overlay in [openshift CI](https://github.com/openshift/release/pull/48886#discussion_r1494483108)

CARRY: Use env variable 'NAMESPACE' for e2e tests

---

.github/workflows/odh-release.yml

CARRY: Add workflow to release ODH/Kueue with compiled test binaries

---

config/components/manager/controller_manager_config.yaml

See https://issues.redhat.com/browse/RHOAIENG-5411.

PATCH: Do not block admission while waiting for pods readiness

---

config/rhoai/kueue-metrics-service.yaml
config/rhoai/kustomization.yaml

Add Service for Kueue metrics

---

Dockerfile.rhoai

https://issues.redhat.com/browse/RHOAIENG-7321

Add dedicated Dockerfile for Konflux

---

Dockerfile.rhoai

use golang version workaround for ubi9 image

---

config/rhoai/prometheus_rule.yaml
docs/alerts/runbooks/kueue-pod-down.md
docs/alerts/runbooks/low-cluster-queue-resource-usage.md
docs/alerts/runbooks/pending-workload-pods.md
docs/alerts/runbooks/resource-reservation-exceeds-quota.md

/kind documentation
This PR adds runbooks for kueue alerts added in this [PR](https://github.com/opendatahub-io/kueue/pull/38).
Fixes #[RHOAIENG-11028](https://issues.redhat.com/browse/RHOAIENG-11028)
Related to [RHOAIENG-1251](https://issues.redhat.com/browse/RHOAIENG-1251)
```release-note
```

CARRY: Adding runbooks for alerts

---

config/rhoai/prometheus_rule.yaml

/kind bug
Updates to use runbook_url in the prometheus rules file to allow this url to be viewed via the OpenShift alerting UI. Also updates the urls to direct users to view the runbooks in the dedicated runbooks repo.
Fixes #[RHOAIENG-11232](https://issues.redhat.com/browse/RHOAIENG-11232)
```release-note
```

CARRY: Updating runbook urls for use on OpenShift alerting UI

---

.github/workflows/odh-build-and-publish-kueue-image.yaml

https://issues.redhat.com/browse/RHOAIENG-11688

Update "odh-build-and-publish-kueue-image" workflow to trigger manually only

---

test/util/e2e.go

https://issues.redhat.com/browse/RHOAIENG-12281

CARRY: Remove check for restarted pod from test suite

---

.github/workflows/odh-release.yml

When running a CodeFlare stack release and the odh-release workflow I did not correctly enter the tag. Updating so this is clearer and release tags are consistent in future.

Updating prompt for release tag

---

OWNERS

The following users havent contributed in the recent past. Moving to emeritus approvers.
- anishasthana
- jbusche
- maxusmusti
- tedhtchang
Fixes #
```release-note
```

Add Emeritus Owners

---

config/rhoai/mutating_webhook_patch.yaml
config/rhoai/validating_webhook_patch.yaml

Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs
Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs
/kind bug
Add openshift namespaces exclusions to prevent kueue validating and mutating webhooks to interfere with system jobs
Uses namespace selector to exclude jobs in relevant openshift-* namespaces to be blocked by kueue mutating and validating webhook in case of kueue being unavailable.
Fixes https://issues.redhat.com/browse/RHOAIENG-14186
none
no
```release-note
Disable kueue-validating-webhook-configuration and kueue-mutating-webhook-configuration for jobs in some openshift-* namespaces to avoid kueue unavailability preventing system jobs to run.
```

PATCH: Exclude openshift namespaces from kueue VWebhook and MWebhook 

---

RELEASE.md
config/component_metadata.yaml

closes https://issues.redhat.com/browse/RHOAIENG-16342
Add the component_metadata.yaml file to track kueue release version
/kind documentation
This PR introduces a new file component_metadata.yaml to track kueue releases. This was a request by the Platform team so they can fetch it to ODH operator and expose in the DSCI
Fixes https://issues.redhat.com/browse/RHOAIENG-16342
no
```release-note
```

RHOAIENG-16342 Add the component_metadata.yaml file to track kueue release version

---

config/rhoai/ocp-4.17-addons/kustomization.yaml
config/rhoai/ocp-4.17-addons/validating_admission_policy.yaml
config/rhoai/ocp-4.17-addons/validating_admission_policy_binding.yaml

Related Jira: https://issues.redhat.com/browse/RHOAIENG-14731

Add Kustomize file for ocp-4.17-addons

---

OWNERS

Add akram and Ygnas to and remove sutaakar from OWNERS

---

config/rhoai/kueue-metrics-service.yaml
config/rhoai/manager_metrics_patch.yaml
config/rhoai/monitor.yaml

Append new metrics port to https-metrics to allow upgrade by operator
